// models/SceneMatchResult.js
const mongoose = require("mongoose");

const SceneMatchSchema = new mongoose.Schema(
  {
    image: String, // filename only (e.g., scene_001.jpg)
    clip_score: Number, // CLIP similarity score
    caption_score: Number, // SentenceTransformer similarity score
    final_score: Number, // Weighted final score
    caption: String, // Caption generated by BLIP
    tags: Object, // Extracted tags: action, place, objects
    yolo_objects: [String], // Detected objects via YOLO
    start_time: String, // Scene start timestamp
    end_time: String, // Scene end timestamp
  },
  { _id: false }
);

const SceneResultSchema = new mongoose.Schema(
  {
    query: String, // Original user query
    title: String, // Movie title or "search_results"
    nlp_tags: Object, // Extracted tags from user query
    matches: [SceneMatchSchema],
    createdAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const UserQuerySchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  result: SceneResultSchema,
  createdAt: { type: Date, default: Date.now },
});

module.exports =
  mongoose.models.SceneMatchResult ||
  mongoose.model("SceneMatchResult", UserQuerySchema);
